name: Demo-2
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      #- uses: actions/checkout@v4
      - name: Welcome message
        run: echo "Hello, world" > hello.txt

      - uses: actions/upload-artifact@v4
        with:
          name: hello-file
          path: hello.txt
    
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:

      #- uses: actions/checkout@v4
      - uses: actions/download-artifact@v5
        with:
          name: hello-file
        
      - name: List file
        run: ls
      - name: Show file content
        run: cat hello.txt |grep -i "Hello, world"
