name: Generate ASCI Artwork
on:
  push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install cowsay program
        run: sudo apt-get install cowsay -y
      - name: Generate ASCI Artwork
        run: cowsay -f dragon "Run for cover, I am a DRAGON-------RAWR" >> dragon.txt
      - name: Test file Exists
        run: grep -i "dragon" dragon.txt
      - name: Read File
        run: cat dragon.txt
      - name: Checkout repo files
        run: ls
    
  
 
