name: Generate ASCI Artwork
on:
  push
jobs:
  builds_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install cowsay program
        run: sudo apt-get install cowsay -y
      - name: Generate ASCI Artwork
        run: cowsay -f dragon "Run for cover, I am a DRAGON-------RAWR" >> dragon.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt
 
  tests_job_2:
    needs: builds_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon File
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
      - name: Test file exists
        run: grep -i "dragon" dragon.txt
  deploy_job_3:
    needs: [tests_job_2]
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon File
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
      
      - name: Read File
        run: cat dragon.txt
      - name: Deploy
        run: echo Deploying now...
    
  
 
